#ifndef HDID_FAMILY_H
#define HDID_FAMILY_H

enum hdid_family_t {
	HDID_FAMILY_UNKNOWN,
	HDID_FAMILY_WD_DESKTOP,
	HDID_FAMILY_WD_RE,
	HDID_FAMILY_WD_RAPTOR,
	HDID_FAMILY_WD_RAPTORX,
	HDID_FAMILY_WD_MOBILE,
	HDID_FAMILY_WD_NAS,
	HDID_FAMILY_WD_VR,
	HDID_FAMILY_WD_XE,
	HDID_FAMILY_WD_S25,
	HDID_FAMILY_WD_BRAND,
	HDID_FAMILY_WD_AV,
	HDID_FAMILY_WD_SERVER,
	HDID_FAMILY_WD_PROTEGE,
};

extern const char *const hdid_family_list[];

#endif
